baseURL = "https://context-of-agile.org/"
languageCode = "en-us"
title = "Context of Agile"


theme = ["book", "plausible-hugo"]


[params]
	# disabled because not working yet
	BookSearch = false

	BookShowToC = true


[params.plausible]
  enable = true
  domain = "context-of-agile.org"
  gitstar = false
